### ISSUE TITLE
force_align.py (TypeError: a bytes-like object is required, not 'str')

### ISSUE THREAD

**Issue by ChristineBasta** [clab/fast_align#58]
Hello,
we are trying to run force_align after using the fast_align, the fast_align is working fine and we get the model.
After running force_align, we get Traceback (most recent call last):
  File "/home/christine/fast_align/build/force_align.py", line 93, in <module>
    main()
  File "/home/christine/fast_align/build/force_align.py", line 87, in main
    sys.stdout.write('{}\n'.format(aligner.align(line.strip())))
  File "/home/christine/fast_align/build/force_align.py", line 30, in align
    self.fwd_align.stdin.write('{}\n'.format(line))
TypeError: a bytes-like object is required, not 'str'

we are running on python 3.6.9.

we do not know where the problem can be from, we are using the right format of sentence:
The mechanic gave the clerk a present because it was his birthday. ||| La mecánica dio al Cirque durargo, porque era su cumpleaños.

please advise!!

**Comment by lluisg** [comment]
We tried changing to bites with 
```sh
        self.fwd_align.stdin.write('{}\n'.format(line).encode('utf-8'))
```
but then the problem persists and gets stuck on the next line
```sh
        fwd_line = self.fwd_align.stdout.readline().split('|||')[2].strip()
```

**Comment by ttwelve12** [comment]
Hi, if you use python3, you should set bufsize = 1 and universal_newlines= True in subprocess.Popen . 
@lluisg @ChristineBasta 
And you can also set the  "encoding" in module subprocess if you meet encode problem

**Comment by lizongyao123** [comment]
Python2
